name: PHPUnit
on:
  push:
    branches:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"

      - name: PHP init 
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.1'
          extension-csv: xdebug
          coverage: xdebug
      - name: php details
        run: php -v
      - name: phpunit exec
        run: php bin/phpunit
